import 'package:get/get.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "enterUsername": "Enter Username",
          "enterPassword": "Enter Password",
          "usernameValidator": "Please enter a valid username",
          "passwordValidator": "Please enter a valid password",
          "enterEmail": "Enter E-Mail",
          "enterMobileNumber": "Enter Mobile Number",
          "forgotPassword": "Forgot Password ?",
          "signIn": "Sign In",
          "createAccount": "Create Account",
          "signUp": "Sign Up",
          "enterMobile": "Enter Mobile Number",
          "mobileCountValidator": "Please Enter 8 digit Password!",
          "confirmPassword": "Confirm Password",
          "emailValidator": "Please enter a valid E-Mail",
          "@notfound": "@ not found",
          "mobileValidator": "Please enter a valid Mobile Number",
          "confirmPasswordValidator": "Password does not match",
          "passwordCountValidator": "Please Enter 8 digit Password!",
          "dashboard": "Dashboard",
          "calender": "Calendar",
          "sports": "Sports",
          "monitoring": "Monitoring",
          "reports": "Reports",
          "newRequest": "New\nRequest",
          "administrator": "Administrator",
          "studentCertificate": "Student\nCertificate",
          "attendance": "Attendance",
          "promoteStudent": "Promote\nStudent",
          "promoteStudents": "Promote Student",
          "overview": "Overview",
          "rediness": "Rediness",
          "trainingLoad": "Training Load",
          "testResults": "Test Results",
          "playerCard": "Player Card",
          "playerUpdate": "Player Update",
          "requests": "Requests",
          "request": "Request",
          "user": "User",
          "name/ApplicationId": "Name/Application Id",
          "chatWithAdmin": "Chat with Admin",
          "downloadCertificate": "Download Certificate",
          "enterStudentId": "Enter Student Id",
          "officialPlayer": "Official Player",
          "school": "School",
          "academy": "Academy",
          "name": "Name",
          "mobile": "Mobile",
          "allcopyrights@AlIbtisam": "All copyrights @Al Ibtisam",
          "areyousureyouwanttologout?": "Are you sure you want to logout?",
          "yes": "Yes",
          "no": "No",
          "home": "Home",
          "myprofile": "My Profile",
          "sendrequest": "Send Request",
          "practice": "Practicce",
          "personalinformation": "Personal Information",
          "performance": "Performance",
          "applyforloan": "Apply for loan",
          "requestitems": "Request Items",
          "certificatedownload": "Certificate\n Download",
          "teamstatics": "Team Statics",
          "usermanagement": "User\nManagement",
          "checkattendance": "Check\nAttendance",
          "collection": "Collection",
          "sessionappointment": "Session\nAppointment",
          "folder": "Folder",
          "wellness": "Wellness",
          "workload": "Workload",
          "health": "Health",
          "nutrition": "Nutrition",
          "hydration": "Hydration",
          "stress": "Stress",
          "sleep": "Sleep",
          "sunday": "Sunday",
          "monday": "Monday",
          "tuesday": "Tuesday",
          "wednesday": "Wednesday",
          "thursday": "Thursday",
          "january": "January",
          "february": "February",
          "march": "March",
          "april": "April",
          "may": "May",
          "basketball": "Basketball",
          "volleyball": "Volleyball",
          "football": "Football",
          "handball": "Handball",
          "badminton": "Badminton",
          "gymnastics": "Gymnastics",
          "profession": "Profession",
          "participationCertificate": "Participation Certificate",
          "achievementCertificate": "Achievement Certificate",
          "recognitionCertificate": "Recognition Certificate",
          "certificate": "Certificate",
          "checkIn": "Check In",
          "checkOut": "Check Out",

          "appointment": "APPOINTMENT",
          "enquery": "Enquery",
          "admission": "Admission",
          "other": "Other",
          "enterYourName": "Enter your name",
          "enterYourEmail": "Enter your E-Mail",
          "enterYourNumber": "Enter your mobile number",
          "appointmentDate": "Appointment Date",
          "submit": "Submit",
          "dateValid": "Please Enter Date",
          "userManagement": "User Management",
          "skip": "Skip >>",
          "switchLanguage": "Switch Language",
          "english": "English",
          "arabic": "Arabic",
          "language": "Language",
          "friends": "Friends",
          "age": "Age",
          "games": "Games",
          "applications": "Applications",
          "playerId": "Player Id :",
          "status": "Status :",
          "view": "View",
          "applicationDetails": "Application Details",
          "applicationDate": "Application Date : 10/10/2023",
          "applicationNo": "Application Number",
          "personalInformation": "Personal Information",
          "fullName": "Full name :-",
          "fatherName": "Father Name :-",
          "motherName": "Mother Name :-",
          "personalId": "Personal ID :-",
          "email": "Email :",
          "mobileNo": "Mobile No :",
          "gender": "Gender :",
          "bloodGroup": "Blood Group :",
          "nationality": "Nationality :",
          "religion": "Religion :",
          "height": "Height (ft)",
          "feet": "Feet",
          "feet/inch": "Feet/Inch :",
          "chestSize": "Chest Size :",
          "cm": "cm",
          "highJump": "High Jump :",
          "lowJump": "Low Jump :",
          "addmisionForm": "Addmision Form",
          "firstName": "First Name *",
          "middleName": "Middle Name",
          "lastNameValid": "Please Enter lastname",
          "fatherNameValid": "Please Enter father name",
          "lastName": "Last Name *",
          "mobileValid": "Please Enter mobile number",
          "dateOfBirthValid": "Please Select Date of Birth",
          "dateOfBirth": "Date Of Birth",
          "emailId": "Email Id",
          "emailValid": " @ Is Not Found!",
          "female": "Female",
          "male": "Male",
          "weightInKg": "Weight (kg)",
          "heightInFeet": "Height (ft)",
          "nextPage": "Next Page",
          "registerFor": "Register for...",
          "selectSport": "Select Sport",
          "selectBatch": "Select Batch",
          "pm": "Pm",
          "highjumpFeet": "High Jump In Feet",
          "longJumpFeet": "Long Jump In Feet",
          "address": "Enter Your Address",
          "country": "Country",
          "state": "State",
          "city": "City",
          "postalCode": "Postal Code",
          "correspondenceAddress": "Correspondence Address",
          "relationWith": "Relation With Applicant",
          "uploadDocuments": "Upload Documents",
          "photo": "Photo",
          "goToPayment": "Go to Payment",
          "requestNewApplication": "Request New Application",
          "practiceVideos": "Practice Videos",
          "youCanEdit": "You can edit your \nprofile here",
          "enterProfession": "Please enter proffession",
          "dob": "Date of Birth",
          "phoneNumber": "Phone Number",
          "update": "update",
          "nameProfession": "Name\nProfession",
          "sno": "SNo",
          "match": "Match",
          "play": "Play",
          "loss": "Loss",
          "win": "Win",
          "download": "Downlaod",
          "loanApplication": "Loan Application",
          "next": "Next",
          "enterBankName": "Enter Bank Name",
          "bankName": "Bank Name",
          "accountNumber": "Account Number",
          "accountType": "Account Type",
          "loanType": "Loan Type",
          "enterAmount": "Enter Amount",
          "reasonForApply": "Reason for Applyin Loan",
          "enterAccountNumber": "Please Enter Account Number",
          "enterAccountType": "Please Enter Account Type",
          "enterLoanType": "Please Loan Type",
          "enterAmmount": "Please Enter Amount",
          "loanApplicationSuccess":
              "Your Loan application has been\nsent to the administration",
          "ok": "Ok",
          "requestItems": "Request Items",
          "enrollNow": "Enroll Now",
          "mediaEvents": "Media Events",
          "store": "Store",
          "about": "About",
          "contact": "Contact",
          "about2":
              "Al-Ibtisam Club, we are dedicated to powering your performance with a comprehensive software solution that goes beyond the ordinary. Our platform is crafted to elevate the coaching experience, providing a suite of tools designed to seamlessly integrate into the dynamic world of modern sports.",
          "welcome": "WELCOME",
          "ourCommitment": "OUR COMMITMENT",
          "about1":
              "Al-Ibtisam Club, where we redefine performance through cutting-edge software solutions tailored for modern clubs and coaches.",
          "event": "Events",
          "location": "Location:",
          "allEvents": "All Events",
          "sportsEvent": "Sports Event",
          "announcements": "Announcements",
          "filter": "Filter",
          "sortBy": "SORT BY",
          "allProduct": "All Products",
          "newToOld": "New To Old",
          "OldToNew": "Old To New",
          "buyNow": "Buy now",
          "noProducts": "No Product Available",
          "rs": "Rs",
          "hurryOnly": "Hurry only",
          "stockLeft": "left in stock",
          "size": "SIZE:",
          "stockOut": "Out of stock",
          "addToCart": "Add to Cart",
          "myCart": "My Cart",
          "total": "Total:",
          "checkOutItem": "CHECKOUT",
          "newEnrollment": "New Enrollment",
          //new keywords
          "profile": "Profile",
          "orderHistory": "Order History",
          "cart": "Cart",
          "privacyT&C": "Privacy and T&C",
          "logOut": "Log Out",
          "fees": "Fees",
          "weight": "Weight (Kg)",
          "paymentStatus": "Payment Status",
          "aaddress": "Address",
          "phone": "Phone",
          "batch": "Batch",
          "front": "Front",
          "back": "Back",
          "applicationProcessed": "Application Processed",

          //26/4/24
          "selectInstitution": "Select Institution*",
          "Dob": "DOB*",
          "uploadIdProof": "Upload Id Proof",
          "uploadCertificate": "Upload Certificate",
          "optional": "(Optional)",
          "requestForm": "Request Form",
          "send": "Send",
          "loanAmount": "Loan Ammount",
          "description": "Description",
          "pleaseinputavalid": "Please input a valid",
          "notifications": "Notifications",
          "tournametRequest": "Tournament Request",
          "analysisRequest": "Analysis Request",
          "otherRequest": "Other Request",
          "updatePlayer": "Update Player",
          "invoice": "Invoice",
          "sessionAppointment": "Session Apointment",
          "chatCategory": "Chat Category",
          "search": "Search...",
          "hello": "Hello...",
          "teams": "Teams",
          "internalMatch": "Internal Match",
          "externalMatch": "External Match",
          "eventName": "Event Name",
          "tournamentRequest": "Tournament Request",
          'select': 'Select',
          'friendly': 'Friendly',
          'scrimmage': 'Scrimmage',
          'trainingPurpose': 'Training Purpose',
          'teamBonding': 'Team Bonding',
          'competitiveExprience': 'Competitive Exprience',
          'promotionalOrCommunity': 'Promotional or Community',
          'engagementPurpose': 'Engagement Purpose',
          'matchType': 'Match Type',
          'selectType': 'Select Type',
          'matchDetails': 'Match Details',
          'time&date': "Time & Date",
          'pleaseSelectaTeam': 'Please select a team',
          'opponent': 'Opponent',
          'purposeoftheMatch': 'Purpose of the Match',
          'estimatedBudget': 'Estimated Budget',
          'additionalNotes': 'Additional Notes',
          "forward": "Forward",
          "tournament": "Tournament",
          "league": "League",
          "applicationNumber": "Application Number: ",
          "available": "Available!!",
          "color": "COLOR: ",
          "sar": "SAR ",
          "teamAttendance": "Team Attendance",
          "player": "Player",
          "in": "In",
          "out": "Out",
          "markAttendanceNote":
              "Note: Once a checkbox is checked the date and time will be recorded against that player.",
          "edit": "Edit",
          "remark": "Remark",
          "submitAttendance": "Submit Attendance",
          "writeAremarkHere": "Write a remark here..",
          "pleasewriteAremarkFirst": "Please write a remark first",
          "remarkAddedSuccessfully": "Remark added successfully",
          "message": "Message",
          "pleaseFillOutTimeForAllPresentPlayers":
              "Please fill out time for all present players",
          "present": "PRESENT",
          "absent": "ABSENT",
          "markedOn": "Marked On: ",
          "noRemarkAdded": "No remark added",
          "clearAll": "Clear All",
          "internal": "Internal",
          "external": "External",
          "teamSize": "Team Size ",
          "players": "Players",
          "readiness": "Readiness",
          "cancel": "Cancel",
          "overall": "Overall",
          "injury": "Injury",
          "save": "Save",
          "report": "Report",
          "tournamentsDetails": "Tournaments Details",
          "requestedOn": "Requested on: ",
          "leaveRequest": "Leave Request",
          "otherRequests": "Other Requests",
          "leaveType": "Leave Type",
          "dates": "Dates",
          "reason": "Reason",
          "days": "Days",
          "Reject": "reject",
          "certificateRequest": "Certificate Request",
          "certificateType": "Certificate Type",
          "date": "Date",
          "requestReject": "Request Reject",
          "invoiceNo": "Invoice No.",
          "items": "Items",
          "pending": "Pending",
          "approved": "Approved",
          "rejected": "Rejected",
          "createInvoice": "Create Invoice",
          //new
          "theme": "Theme",
          "settings": "Settings",
          "announcementEvent": "ANNOUNCEMENT EVENT",
          "sportEvent": "SPORT EVENT",
          "events": "Events",
          "globalEvents": "GLOBAL EVENTS",
          "myEvents": "My EVENTS",
          "userName&Email": "Username or Email",
          "password": "Password",
          "login": "Login",
          "dontHaveAnAcoount": "Don't have an acoount?",
          "sportsClub": "Sports Club",
          "alreadyHaveAnAcoount": "Already have an acoount?",
          "team": "Team ",
          "playerName": "Player Name",
          "statistics": "Statistics",
          "history": "History",
          "measurementRequest": "Measurement Request",
          "game": "Game",
          "idProofBack": "ID PROOF BACK",
          "idProofFront": "ID PROOF FRONT",
          "newForm": "New Form",
          "pleasePickAllMendatoryImages": "Please Pick All Mendatory Images",
          "submitForm": "Submit Form",
          "chat": "Chat",
          "areYouSureYouWantToExit": "Are You Sure You Want to Exit ?",
          "areYouSureYouWantToLogOut": "Are You Sure You Want to Log Out ?",
          "role": "Role",
          "userName": "User Name",
          "switchUser": "Switch User",
          "light": "Light",
          "dark": "Dark",
          "confirm": "Confirm",
          "foundedOn": "Founded on",
          "mission": "Mission",
          "vision": "Vision",
          "registrationNumber": "Registration Number",
          "socialMedia": "Social Media",
          "typeYourMessage": "Type your message...",

          //---new keywords
          "wereHereToHelp": "We're here to help!",
          "ifYouHaveAnyQuestion":
              "If you have any questions or need assistance, feel free to reach out to us.",
          "zohoForm": "Zoho form",
          "contactUsOnWhatsapp": "Contact Us on WhatsApp",
          "emailUs": "Email Us",
          "help&support": "Help & Support",
          "deleteAccount": "Delete Account",
          "selectstage": "Select Stage",
          "noGroupsFound": "No Groups found",
          "createRequest": "Create Request",
          "internalTournament": "Internal Tournament",
          "externalTournament": "External Tournament",
          "Description": "Description",
          "Team Name": "Team Name",
          "Done": "Done",
          "Select Players": "Select Players",
          "Select Coaches": "Select Coaches",
          "Requested Amount": "Requested Amount",
          "Start Date & End Date": "Start Date & End Date",
          "From": "From",
          "To": "To",
          "Transport Medium": "Transport Medium",
          "Travel Date": "Travel Date",
          "Expected Departure": "Expected Departure",
          "Tournament Request": "Tournament Request",
          "View Tournament": "View Tournament",
          "Type": "Type",
          "Start Date": "Start Date",
          "End Date": "End Date",
          "Tournament": "Tournament",
          "Location": "Location",
          "Expected Arrival": "Expected Arrival",
          "Players": "Players",
          "Coaches": "Coaches",
          "Age": "Age",
          "Write your remark..": "Write your remark..",
          "ADD REMARK": "ADD REMARK",
          "attendanceHistory": "attendanceHistory",
          "Alibtisam Store": "Alibtisam Store",
          "Player Polarization": "Player Polarization",
          "VIEW DETAILS": "VIEW DETAILS",
          "Current Game": "Current Game",
          "Current Stage": "Current Stage",
          "Manage Groups": "Manage Groups",
          "Please Select a group": "Please Select a group",
          "Are you sure you want update": "Are you sure you want update",
          "stage": "stage",
          "Update Stage From": "Update Stage From",
          "Confirm": "Confirm",
          "Update Stage": "Update Stage",
        },
        'ar_DZ': {
          "enterUsername": "أدخل اسم المستخدم",
          "enterPassword": "أدخل كلمة المرور",
          "usernameValidator": "الرجاء إدخال اسم مستخدم صحيح",
          "passwordValidator": ",الرجاء إدخال كلمة مرور صحيحة",
          "enterEmail": "أدخل البريد الإلكتروني",
          "enterMobileNumber": "أدخل رقم الجوال",
          "forgotPassword": "نسيت كلمة المرور؟",
          "signIn": "تسجيل الدخول",
          "createAccount": "إنشاء حساب",
          "signUp": "إنشاء حساب",
          "enterMobile": "أدخل رقم الجوال",
          "mobileCountValidator": ",الرجاء إدخال 8 خانات",
          "confirmPassword": "تأكيد كلمة المرور",
          "emailValidator": "الرجاء إدخال بريد إلكتروني صحيح",
          "@notfound": "غير موجود",
          "mobileValidator": "الرجاء إدخال رقم جوال صحيح",
          "confirmPasswordValidator": "كلمة المرور غير متطابقة",
          "passwordCountValidator": "الرجاء إدخال 8 خانات",
          "dashboard": "لوحة التحكم",
          "calender": "التقويم",
          "sports": "الرياضات",
          "monitoring": "التحكم",
          "reports": "التقارير",
          "newRequest": "طلب جديد",
          "administrator": "الإدارة",
          "studentCertificate": "شهادة الطالب",
          "attendance": "الحضور",
          "promoteStudent": "ترقية الطالب",
          "promoteStudents": "ترقية الطالب",
          "overview": "نظرة عامة",
          "rediness": "استعداد",
          "trainingLoad": "الجهد في التدريب",
          "testResults": "نتائج الاختبار",
          "playerCard": "بطاقة اللاعب",
          "playerUpdate": "تحديث اللاعب",
          "requests": "الطلبات",
          "request": ",الطلب",
          "user": "المستخدم",
          "name/ApplicationId": "معرف الاسم/الطلب",
          "chatWithAdmin": "الدردشة مع المسؤول",
          "downloadCertificate": "تحميل الشهادة",
          "enterStudentId": "أدخل معرف الطالب",
          "officialPlayer": "لاعب رسمي",
          "school": "مدرسة",
          "academy": "أكاديمية",
          "name": "الإسم",
          "mobile": "الجوال",
          "allcopyrights@AlIbtisam": "جميع الحقوق محفوظة الى نادي الابتسام",
          "areyousureyouwanttologout?": "هل أنت متأكد من تسجيل الخروج؟",
          "yes": "نعم",
          "no": "لا",
          "home": "الصفحة الرئيسية",
          "myprofile": "ملفي الشخصي",
          "sendrequest": "إرسال طلب",
          "practice": "تدريب",
          "personalinformation": "المعلومات الشخصية",
          "performance": "الأداء",
          "applyforloan": "طلب سُلفة",
          "requestitems": "طلب سلع",
          "certificatedownload": "تحميل شهادة",
          "teamstatics": "إحصائيات الفريق",
          "usermanagement": "إدارة المستخدم",
          "checkattendance": "التحقق من الحضور",
          "collection": "مجموعة",
          "sessionappointment": "موعد جلسة",
          "folder": "ملف",
          "wellness": "الاستشفاء",
          "workload": "عبء العمل",
          "health": "الصحة",
          "nutrition": "التغذية",
          "hydration": "الارتواء",
          "stress": "التوتر",
          "sleep": "النوم",
          "sunday": "الأحد",
          "monday": "الإثنين",
          "tuesday": "الثلاثاء",
          "wednesday": "الأربعاء",
          "thursday": "الخميس",
          "january": "يناير",
          "february": "فبراير",
          "march": "مارس",
          "april": "ابريل",
          "may": "مايو",
          "basketball": "كرة السلة",
          "volleyball": "كرة الطائرة",
          "football": "كرة القدم",
          "handball": "كرة اليد",
          "badminton": "الريشة الطائرة",
          "gymnastics": "الجمباز",
          "profession": "الوظيفة",
          "participationCertificate": "شهادة ممارس",
          "achievementCertificate": "شهادة الإنجاز",
          "recognitionCertificate": "شهادة التعريف",
          "certificate": "شهادة",
          "checkIn": "تسجيل الدخول",
          "checkOut": "تسجيل الخروج",
          "appointment": "موعد",
          "enquery": "استفسار",
          "admission": "القبول",
          "other": "أخرى",
          "enterYourName": "أدخل الإسم",
          "enterYourEmail": "أدخل البريد الإلكتروني",
          "enterYourNumber": "أدخل رقم الجوال",
          "appointmentDate": "تاريخ الموعد",
          "submit": "تقديم,",
          "dateValid": "الرجاء إدخال التاريخ",
          "userManagement": "إدارة المستخدم",
          "skip": "تخطي >>",
          "switchLanguage": "تغيير اللغة",
          "english": "الإنجليزية",
          "arabic": "العربية",
          "language": "اللغة",
          "friends": "الأصدقاء",
          "age": "العمر",
          "games": "الألعاب",
          "applications": "الطلبات",
          "playerId": "رقم اللاعب",
          "status": "الحالة",
          "view": "معاينة",
          "applicationDetails": "تفاصيل الطلب",
          "applicationDate": "تاريخ الطلب: 10/10/2023",
          "applicationNo": "رقم الطلب",
          "personalInformation": "المعلومات الشخصية",
          "fullName": "الإسم الكامل",
          "fatherName": "اسم الأب",
          "motherName": "اسم الأم",
          "personalId": "رقم الهوية",
          "email": "البريد الإلكتروني",
          "mobileNo": "رقم الجوال",
          "gender": "الجنس",
          "bloodGroup": "فصيلة الدم",
          "nationality": "الجنسية",
          "religion": "الدين",
          "height": "الطول",
          "feet": "قدم",
          "feet/inch": "قدم/إنش: ",
          "chestSize": "مقاس الصدر",
          "cm": "سم",
          "highJump": "قفزة عالية",
          "lowJump": "قفزة منخفضة",
          "addmisionForm": "استمارة القبول",
          "firstName": "الإسم الأول",
          "middleName": "الإسم الثاني",
          "lastNameValid": "اسم العائلة",
          "fatherNameValid": "اسم الأب",
          "lastName": "الإسم الآخر",
          "mobileValid": "الرجاء إدخال رقم االجوال",
          "dateOfBirthValid": "الرجاء اختيار تاريخ الميلاد",
          "dateOfBirth": "تاريخ الميلاد",
          "emailId": "عنوان البريد الإلكتروني",
          "emailValid": " @ غير موجود",
          "female": "أنثى",
          "male": "ذكر",
          "weightInKg": "الوزن بالكجم",
          "heightInFeet": "الطول بالقدم",
          "nextPage": "الصفحة التالية",
          "registerFor": "التسجيل في… ",
          "selectSport": "اختيار الرياضة",
          "selectBatch": "اختيار حزمة",
          "pm": "مساء",
          "highjumpFeet": "القفزة العالية بالقدم",
          "longJumpFeet": "القفزة المنخفضة بالقدم",
          "address": "أدخل عنوانك",
          "country": "الدولة",
          "state": "الولاية",
          "city": "المدينة",
          "postalCode": "الرمز البريدي",
          "correspondenceAddress": "عنوان المراسلة",
          "relationWith": "العلاقة مع مقدم الطلب",
          "photo": "صورة",
          "goToPayment": "الذهاب للدفع",
          "requestNewApplication": "طلب جديد",
          "practiceVideos": "فيديوهات التدريب",
          "youCanEdit": "من هنا يمكنك تعديل ملفك الشخصي",
          "enterProfession": "أدخل مهنتك",
          "dob": "تاريخ الميلاد",
          "phoneNumber": "رقم الجوال",
          "update": "تحديث",
          "nameProfession": "مهنة/اسم",
          "sno": "SNo",
          "match": "مباراة",
          "play": "لعبة",
          "loss": "خسارة",
          "win": "فوز",
          "download": "تحميل",
          "loanApplication": "شهادة السُلفة",
          "next": "التالي",
          "enterBankName": "الرجاء إدخال اسم البنك",
          "bankName": "اسم البنك",
          "accountNumber": "رقم الحساب",
          "accountType": "نوع الحساب",
          "loanType": "نوع السُلفة",
          "enterAmount": "إدخال القيمة",
          "reasonForApply": "سبب طلب السُلفة",
          "enterAccountNumber": "الرجاء إدخال رقم الحساب",
          "enterAccountType": "الرجاء إدخال نوع الحساب",
          "enterLoanType": "الرجاء إدخال نوع السُلفة",
          "enterAmmount": "الرجاء إدخال القيمة",
          "loanApplicationSuccess": "طلبك للسُلفة/ تم إرساله إلى الإدارة",
          "ok": "حسناً",
          "requestItems": "طلب سلع",
          "enrollNow": "انضم الآن",
          "mediaEvents": "الأحداث الإعلامية",
          "store": "المتجر",
          "about": "عن",
          "contact": "التواصل",
          "about2":
              "نادي الإبتسام,نحن ملتزمون بتطوير أدائك من خلال حلول برمجية شاملة تتجاوز المألوف,تم تصميم منصتنا لرفع تجربة التدريب,وتوفير مجموعة من الأدوات المصممة للاندماج بسلاسة في العالم الرياضي الرقمي الحديث",
          "welcome": "أهلاً وسهلاً",
          "ourCommitment": "التزاماتنا",
          "about1":
              "نادي الإبتسام, حيث نعيد تعريف الأداء من خلال حلول برمجية متطورة مصممة خصيصاً للأندية والمدربين",
          "event": "الأحداث",
          "location": "الموقع",
          "allEvents": "كل الأحداث",
          "sportsEvent": "الأحداث الرياضية",
          "announcements": "الإعلانات",
          "filter": "تصفية",
          "sortBy": "ترتيب حسب",
          "allProduct": "جميع المنتجات",
          "newToOld": "من الأجدد إلى الأقدم",
          "OldToNew": "من الاقدم الى الأجدد",
          "buyNow": "شراء الآن",
          "noProducts": "السلعة غير متوفرة",
          "rs": "Rs",
          "hurryOnly": "السرعة فقط",
          "stockLeft": "المتبقي في المخزون",
          "size": "المقاس",
          "stockOut": "نفذ من المخزون",
          "addToCart": "إضافة للعربة",
          "myCart": "عربتي",
          "total": "المجموع",
          "checkOutItem": "الذهاب للدفع",
          "newEnrollment": " تسجيل جديد ",

          //------
          "profile": "التعريف",
          "cart": "عربة التسوق",

          "privacyT&C": "الخصوصية والشروط والأحكام",
          "logOut": "تسجيل خروج",
          "fees": "الرسوم",
          "weight": "الوزن",
          "paymentStatus": "حالة السداد",
          "aaddress": "العنوان",
          "phone": "الجوال",
          "batch": "الدفعة",
          "front": "الامام",
          "back": "الخلف",
          "applicationProcessed": "تمت معالجة الطلب",
          "selectInstitution": "اختبار المركز",
          "Dob": "DOB*",
          "uploadIdProof": "تحميل إثبات الهوية",
          "uploadCertificate": "تحميل الشهادة",
          "optional": "(اختياري)",
          "requestForm": "نموذج الطلب",
          "send": "ارسال",
          "loanAmount": "مبلغ القرض",
          "description": "الوصف",
          "pleaseinputavalid": "برجاء ادخال الصالح",
          "notifications": "الإخطارات",
          "tournametRequest": "طلب بطولة",
          "analysisRequest": "طلب تحليل",
          "otherRequest": "الطلبات الأخرى",
          "updatePlayer": "تحديث اللاعب",
          "invoice": "فاتورة",
          "sessionAppointment": "موعد الجلسة",
          "chatCategory": "درجة المحادثات",
          "search": "بحث...",
          "hello": "اهلا...",
          "teams": "الفريق",
          "internalMatch": "مباراة داخلية",
          "externalMatch": "مباراة خارجية",
          "eventName": "اسم الحدث",
          "tournamentRequest": "طلب بطولة",
          'select': 'اختار',
          'friendly': 'ودي',
          'scrimmage': 'مناورة',
          'trainingPurpose': 'الغرض من التدريب',
          'teamBonding': 'ترابط الفريق',
          'competitiveExprience': 'الخبرة التنافسية',
          'promotionalOrCommunity': 'ترويجية أو مجتمعية',
          'engagementPurpose': 'الغرض من المشاركة',
          'matchType': 'نوع المباراة',
          'selectType': 'اختر النوع',
          'matchDetails': 'Match Details',
          'time&date': "اليوم و الوقت",
          'pleaseSelectaTeam': 'فضلاً اختيار الفريق',
          'opponent': 'الخصم',
          'purposeoftheMatch': 'الغرض من المباراة',
          'estimatedBudget': 'الميزانية المتوقعة',
          'additionalNotes': 'ملاحظات إضافية',
          "forward": "إحالة",
          "tournament": "البطولة",
          "league": "دوري",
          "applicationNumber": "رقم الطلب ",
          "available": "متوفر",
          "color": "اللون ",
          "sar": "ريال سعودي ",
          "teamAttendance": "حضور الفريق",
          "player": "لاعب",
          "in": "داخل",
          "out": "خارج",
          "markAttendanceNote":
              "ملاحظة: بمجرد تحديد مربع الاختيار سيتم تجديد التاريخ والوقت لهذا اللاعب",
          "edit": "تعديل",
          "remark": "ملاحظة",
          "submitAttendance": "إرسال الحضور",
          "writeAremarkHere": "اكتب ملاحظة هنا",
          "pleasewriteAremarkFirst": "فضلاً كتابة الملاحظة اولاً",
          "remarkAddedSuccessfully": "تمت إضافة الملاحظة بنجاح ",
          "message": "رسالة",

          "pleaseFillOutTimeForAllPresentPlayers":
              "يرجى ملء الوقت لجميع اللاعبين الحاضرين",
          "present": "حاضر",
          "absent": "غائب",
          "markedOn": "تم وضع علامة على",
          "noRemarkAdded": "لم يتم وضع ملاحظة",
          "clearAll": "مسح الكل",
          "internal": "داخلي",
          "external": "خارجي",
          "teamSize": " مقاس النوع",
          "players": "لاعب",
          "readiness": "استعداد",
          "cancel": "إلغاء",
          "overall": "بالمجمل",
          "injury": "إصابة",
          "save": "حفظ",
          "report": "تقرير",
          "tournamentsDetails": "تفاصيل البطولات ",
          "requestedOn": "طلب في ",
          "leaveRequest": "طلب اجازة",
          "otherRequests": "الطلبات الأخرى",
          "leaveType": "نوع الاجازة",
          "dates": "التواريخ",
          "reason": "السبب",
          "days": "اليوم",
          "Reject": "مرفوض",
          "certificateRequest": "طلب شهادة",
          "certificateType": "نوع الشهادة",
          "date": "تاريخ",
          "requestReject": "الطلب مرفوض",
          "invoiceNo": "رقم الفاتورة",
          "items": "الاصناف",
          "pending": "متبقي",
          "approved": "معتمد",
          "rejected": "مرفوض",
          "createInvoice": " إنشاء فاتورة",
          "theme": "الموضوع",
          "settings": "اعدادات",
          "announcementEvent": "إعلان حدث",
          "sportEvent": "حدث رياضي",
          "events": "حدث",
          "globalEvents": "حدث عالمي",
          "myEvents": "احداثنا",
          "userName&Email": "اسم المستخدم او البريد الالكتروتي",
          "password": "رمز المرور",
          "login": "دخول",
          "dontHaveAnAcoount": "ليس لدي حساب",
          "sportsClub": "نادي رياضي",
          "alreadyHaveAnAcoount": " لدي حساب مسبق",
          "team": "الفريق ",
          "playerName": "اسم اللاعب",
          "statistics": "الاحصاءات",
          "history": "المحفوظات",
          "measurementRequest": "طلب قياس",
          "game": "لعبة",
          "idProofBack": "إثبات الهوية",
          "idProofFront": "طباعة إثبات الهوية",
          "newForm": "نموذج جديد",
          "pleasePickAllMendatoryImages": "يرجى اختيار جميع الصور",
          "submitForm": "إرسال النموذج",
          "chat": "محادثة",
          "areYouSureYouWantToExit": "هل انت واثق من طلب الخروج",
          "areYouSureYouWantToLogOut": "هل انت واثق من طلب المغادرة",
          "role": "دور",
          "userName": "اسم المستخدم",
          "switchUser": "تبديل المستخدم",
          "light": "مظيئ",
          "dark": "مظلم",
          "confirm": "تأكيد",
          "foundedOn": "متأسس",
          "mission": "مهمة",
          "vision": "رؤية",
          "registrationNumber": "رقم التسجيل",
          "socialMedia": "وسائل التواصل الاجتماعي",
          "typeYourMessage": "...اكتب رسالتك",
        },
      };
}
