import 'package:get/get.dart';

class WebLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Sign in to your account": "Sign in to your account",
          "user name or email address": "user name or email address",
          "Password": "Password",
          "Remember me": "Remember me",
          "Forgot password?": "Forgot password?",
          "Sign In": "Sign In",
          "Profile": "Profile",
          "Settings": "Settings",
          "Billing": "Billing",
          "Total Views": "Total Views",
          "Searce for users": "Searce for users",
          "S.No.": "S.No.",
          "USER NAME": "USER NAME",
          "PHONE": "PHONE",
          "JOB TITLE": "JOB TITLE",
          "STATUS": "STATUS",
          "ACTION": "ACTION",
          "Create User": "Create User",
          "Edit": "Edit",
          "InActive": "InActive",
          "Active": "Active",
          "Create New User": "Create New User",
          "User Details": "User Details",
          "Full Details": "Full Details",
          "Full Name": "Full Name",
          "Gender": "Gender",
          "Mobile": "Mobile",
          "Email Address": "Email Address",
          "Job Title": "Job Title",
          "Select Role": "Select Role",
          "Select Option": "Select Option",
          "Male": "Male",
          "Female": "Female",
          "Other": "Other",
          "Confirm Password": "Confirm Password",
          "Show": "Show",
          "Search for users": "Search for users",
          "LOGO": "LOGO",
          "CLUB NAME": "CLUB NAME",
          "ADMIN NAME": "ADMIN NAME",
          "CLUB DESIGNATION": "CLUB DESIGNATION",
          "MOBILE": "MOBILE",
          "Create Club Admin": "Create Club Admin",
          "S.NO.": "S.NO.",
          "NAME": "NAME",
          "PHONE NO.": "PHONE NO.",
          "EMAIL": "EMAIL",
          "DATE": "DATE",
          "PRODUCT NAME": "PRODUCT NAME",
          "QUANTITY": "QUANTITY",
          "PRICE	ACTION": "PRICE	ACTION",
          "Create SalesLadger": "Create SalesLadger",
          "Search for team": "Search for team",
          "MATCHES":"MATCHES",
          "START DATE":"START DATE",
          "END DATE":"END DATE",
          "ACTION REQUIRED":"ACTION REQUIRED",
          "Create Tournament":"Create Tournament",
          "Teams":"Teams",
          "Description":"Description",
          "EVENT":"EVENT",
          "TEAM/INDIVIDUAL":"TEAM/INDIVIDUAL",
          "VIEW":"VIEW",
          "Create Award":"Create Award",
          "NOTICE TITLE":"NOTICE TITLE",
          "NOTICE MESSAGE":"NOTICE MESSAGE",
          "CREATED DATE/TIME":"CREATED DATE/TIME",
          "TYPE":"TYPE",
          "EXPIRATION DATE":"EXPIRATION DATE",
          "Create Notice":"Create Notice",
          "Create Collection":"Create Collection",
          "GAME NAME":"GAME NAME",
          "STAGE":"STAGE",
          "Create Game":"Create Game",
          "TEAM NAME":"TEAM NAME",
          "COACH NAME":"COACH NAME",
          "TOTAL PLAYER":"TOTAL PLAYER",
          "PLAYING PLAYER":"PLAYING PLAYER",
          "Create New Team":"Create New Team",
          "Number Of Players":"Number Of Players",
          "Playing Players":"Playing Players",
          "Submit":"Submit",
          "CONTACT NO.":"CONTACT NO.",
          "PLAYER NAME":"PLAYER NAME",
          "CITY":"CITY",
          "Back":"Back",
          "Assign Team":"Assign Team",
          "Member since":"Member since",
          "About":"About",
          "Current Address":"Current Address",
          "User Name":"User Name",
          "Permanant Address":"Permanant Address",
          "Birthday":"Birthday",
          "EXPERIENCE":"EXPERIENCE",
          "SPECIALIZATION":"SPECIALIZATION",
          "Create Coach":"Create Coach",
          "Email address":"Email address",
          "Experience (In years)":"Experience (In years)",
          "Date Of Birth":"Date Of Birth",
          "Select Game":"Select Game",
          "Create New Coach":"Create New Coach",
          "REQUESTED BY":"REQUESTED BY",
          "REQUEST TYPE":"REQUEST TYPE",
          "REQUEST STATUS":"REQUEST STATUS",
          "Select Filter":"Select Filter",
          "Modal Title":"Modal Title",
          "Pending Request":"Pending Request",
          "Approved Request":"Approved Request",
          "Rejected Request":"Rejected Request",
          "Create Request":"Create Request",
          "TOURNAMENT":"TOURNAMENT",
          "DESCRIPTION":"DESCRIPTION",
          "WINNER TEAM":"WINNER TEAM",
          "Application Services:":"Application Services:",
          "Events":"Events",
          "Sports":"Sports",
          "Statistics":"Statistics",
          "Measurement":"Measurement",
          "Tournament Request":"Tournament Request",
          "Attendance":"Attendance",
          "Practice":"Practice",
          "Store":"Store",
          "Request Portal":"Request Portal",
          "Player Polarization":"Player Polarization",
          "Session Appointment":"Session Appointment",
          "Loan application":"Loan application",
          "Enrollment":"Enrollment",
          "Collection":"Collection",
          "Chat":"Chat",
          "Accessible To:":"Accessible To:",
          "EXTERNAL USER":"EXTERNAL USER",
          "INTERNAL USER":"INTERNAL USER",
          "COACH":"COACH",
          "GUARDIAN":"GUARDIAN",
          "Edit Access Roles":"Edit Access Roles",
          "Sign Out":"Sign Out",
          "CATEGORY":"CATEGORY",
          "TIME":"TIME",
          "LOCATION":"LOCATION",
          "Category":"Category",
          "Date & Time":"Date & Time",
          "ANNOUNCEMENT EVENT":"ANNOUNCEMENT EVENT",
          "SPORT EVENT":"SPORT EVENT",
          "GENERAL EVENT":"GENERAL EVENT",
          "Game Category":"Game Category",
          "Next":"Next",
          "Brief description for your Event":"Brief description for your Event",
          "Create New Event":"Create New Event",
          "Upload Banner":"Upload Banner",
          "Tournament Name":"Tournament Name",
          "Select Teams":"Select Teams",
          "Numbers of Matches":"Numbers of Matches",
          "Select Status":"Select Status",
          "Upcoming":"Upcoming",
          "Ongoing":"Ongoing",
          "Completed":"Completed",
          "Close":"Close",
          "Tournament Details":"Tournament Details",
          "Additional Notes":"Additional Notes",
          "Individual":"Individual",
          "Media":"Media",
          "Create New Notice":"Create New Notice",
          "Content":"Content",
          "Title":"Title",
          "Type":"Type",
          "ValidTill":"ValidTill",
          "Panel Permissions":"Panel Permissions",
          "Media Center":"Media Center",
          "Inventory":"Inventory",
          "Game Manager":"Game Manager",
          "Operation":"Operation",
          "All":"All",
          "All Create":"All Create",
          "All Read":"All Read",
          "All Update":"All Update",
          "All Delete":"All Delete",
          "Create":"Create",
          "Read":"Read",
          "Update":"Update",
          "Delete":"Delete",
        }
      };
}
