import 'package:get/get.dart';

class WebLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Sign in to your account": "Sign in to your account",
          "user name or email address": "user name or email address",
          "Password": "Password",
          "Remember me": "Remember me",
          "Forgot password?": "Forgot password?",
          "Sign In": "Sign In",
          "Profile": "Profile",
          "Settings": "Settings",
          "Billing": "Billing",
          "Total Views": "Total Views",
          "Searce for users": "Searce for users",
          "S.No.": "S.No.",
          "USER NAME": "USER NAME",
          "PHONE": "PHONE",
          "JOB TITLE": "JOB TITLE",
          "STATUS": "STATUS",
          "ACTION": "ACTION",
          "Create User": "Create User",
          "Edit": "Edit",
          "InActive": "InActive",
          "Active": "Active",
          "Create New User": "Create New User",
          "User Details": "User Details",
          "Full Details": "Full Details",
          "Full Name": "Full Name",
          "Gender": "Gender",
          "Mobile": "Mobile",
          "Email Address": "Email Address",
          "Job Title": "Job Title",
          "Select Role": "Select Role",
          "Select Option": "Select Option",
          "Male": "Male",
          "Female": "Female",
          "Other": "Other",
          "Confirm Password": "Confirm Password",
          "Show": "Show",
          "Search for users": "Search for users",
          "LOGO": "LOGO",
          "CLUB NAME": "CLUB NAME",
          "ADMIN NAME": "ADMIN NAME",
          "CLUB DESIGNATION": "CLUB DESIGNATION",
          "MOBILE": "MOBILE",
          "Create Club Admin": "Create Club Admin",
          "S.NO.": "S.NO.",
          "NAME": "NAME",
          "PHONE NO.": "PHONE NO.",
          "EMAIL": "EMAIL",
          "DATE": "DATE",
          "PRODUCT NAME": "PRODUCT NAME",
          "QUANTITY": "QUANTITY",
          "PRICE	ACTION": "PRICE	ACTION",
          "Create SalesLadger": "Create SalesLadger",
          "Search for team": "Search for team",
        }
      };
}
